version: "3"
services:
  rabbitmq:
    image: rabbitmq:3.9
    ports:
      - 5672:5672
      - 15672:15672
      - 1883:1883
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: python mqtt.py
